caseStudy/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

caseStudy/force-app/main/default/objects/Project__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

caseStudy/force-app/main/default/classes/TestUtility.cls
@isTest
public class TestUtility {
    
    public static Account prepareAccount(String name){
        Account acc = new Account(
        	Name = name
        );
        
        return acc;
    }
    
    public static List<Account> prepareAccount(Integer numOfRecords, String name){
        List<Account> accountList = new List<Account>();
        for(Integer i=0; i<numOfRecords; i++){
            Account accRecords = new Account();
            accRecords.Name = name+' '+i;
            accRecords.Industry = 'Technology';
            accountList.add(accRecords);
        }
        
        return accountList;
    }
    
    public static Project__c prepareProject(String name,Decimal budget){
        Project__c prj = new Project__c(
        	Name = name,
            Budget__c = budget
        );
        
        return prj;
    }
    
    public static List<Project__c> prepareProject(Integer numOfRecords, String name,Id accountId, Decimal budget){
        List<Project__c> projectList = new List<Project__c>();
        for(Integer i=0; i<numOfRecords; i++){
            Project__c projRecords = new Project__c();
            projRecords.Name = name+' '+i;
            projRecords.Account__c = accountId;
            projRecords.Budget__c = budget;
            projectList.add(projRecords);
        }
        
        return projectList;
    }

}