caseStudy/force-app/main/default/objects/Account/fields/Total_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Projects__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of related Projects. Maintained by ProjectTrigger.</description>
    <label>Total Projects</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

caseStudy/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

caseStudy/force-app/main/default/classes/ProjectTriggerHandler.cls
public class ProjectTriggerHandler {
    
    public static void updateProjectCounts(Map<Id, Project__c> newProjectMap, Map<Id, Project__c> oldProjectMap){

    Set<Id> accountIds = new Set<Id>();

    if(newProjectMap != null) {

        for(Project__c proj : newProjectMap.values()) {

            if(proj.Account__c != null) {
                accountIds.add(proj.Account__c);
            }

            if(oldProjectMap != null &&
               oldProjectMap.containsKey(proj.Id)) {

                Project__c oldProj = oldProjectMap.get(proj.Id);

                if(oldProj.Account__c != null &&
                   oldProj.Account__c != proj.Account__c) {

                    accountIds.add(oldProj.Account__c);
                }
            }
        }
    }

    if(newProjectMap == null && oldProjectMap != null) {

        for(Project__c oldProj : oldProjectMap.values()) {

            if(oldProj.Account__c != null) {
                accountIds.add(oldProj.Account__c);
            }
        }
    }

    if(accountIds.isEmpty()) {
        return;
    }

        List<AggregateResult> aggregateResult = [
        SELECT Account__c accountId,
               COUNT(Id) totalProject
        FROM Project__c
        WHERE Account__c IN :accountIds
        GROUP BY Account__c
    ];

    List<Account> accToUpdate = new List<Account>();

    for(AggregateResult ag : aggregateResult){
        Id accId = (Id) ag.get('accountId');
        Integer total = (Integer) ag.get('totalProject');
        Account acc = new Account();
        acc.Id = accId;
        acc.Total_Projects__c = total;
        accToUpdate.add(acc);

        accountIds.remove(accId);
    }

    for(Id accId : accountIds){
        Account acc = new Account();
        acc.Id = accId;
        acc.Total_Projects__c = 0;
        accToUpdate.add(acc);
    }

    if(accToUpdate.size() > 0){
        update accToUpdate;
    }
}
    

}
        
        
        